version: 2.1

orbs: 
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.0.1

workflows:
  build_test_deploy:
    jobs:
      - build_test
      - deploy_docker:
          requires:
            - build_test
          #filters:
            #branches:
              #only:
                #- main
      - deploy_heroku:
          requires:
            - deploy_docker
          #filters:
            #branches:
              #only:
                #- main


jobs:
  build_test:
    docker:
      - image: circleci/python:3.8.4
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8
            pytest

  deploy_docker:
    docker:
      - image: circleci/python:3.8.4
    
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t "$CIRCLE_SHA1" .
            docker tag "$CIRCLE_SHA1" "$DOCKERHUB_USERNAME"/oc_lettings:"$CIRCLE_SHA1"
            docker push "$DOCKERHUB_USERNAME"/oc_lettings:"$CIRCLE_SHA1"

  deploy_heroku:
    machine: true
    steps:
      - checkout
      - run:
          name: Build app and send Docker IMG to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a oc-lettings2022 web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a oc-lettings2022 web
