version: 2.1

orbs: 
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.0.1

workflows:
  build_test_deploy:
    jobs:
      - build_test
      - deploy_docker:
          requires:
            - build_test
          #filters:
            #branches:
              #only:
                #- main


jobs:
  build_test:
    docker:
      - image: circleci/python:3.8.4
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd Python-OC-Lettings-FR
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd Python-OC-Lettings-FR
            flake8
            pytest

  deploy_docker:
    docker:
      - image: circleci/python:3.8.4

    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/oc-lettings
          extra_build_args: "-t $DOCKER_LOGIN/oc-lettings"
          tag: $CIRCLE_SHA1
      - docker/push:
          image: $DOCKER_LOGIN/oc-lettings
          tag: "latest"
      - docker/push:
          image: $DOCKER_LOGIN/oc-lettings
          tag: $CIRCLE_SHA1
      - checkout